Repository KDT3-MiniProject-8/MiniProject-BE, pull requests merged in 2023-02, with the labels that each got.

#4 Feat: 멤버, 아이템, 장바구니 엔티티 생성
  src/main/java/com/example/miniprojectbe/dto/BasketId.java
  src/main/java/com/example/miniprojectbe/entity/Basket.java
  src/main/java/com/example/miniprojectbe/entity/Deposit.java
  src/main/java/com/example/miniprojectbe/entity/Item.java
  src/main/java/com/example/miniprojectbe/entity/Loan.java
  src/main/java/com/example/miniprojectbe/entity/Member.java
  src/main/resources/application.properties
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Feature

#9 Feat: 회원 서비스 - 로그아웃 개발 (#6)
  src/main/java/com/example/miniprojectbe/controller/LogoutController.java
  src/main/java/com/example/miniprojectbe/entity/Blacklist.java
  src/main/java/com/example/miniprojectbe/repository/BlacklistRepository.java
  src/main/java/com/example/miniprojectbe/service/LogoutService.java
Labels: For: API, Priority: High, Status: Completed, Type: Feature

#10 Feat: 회원 서비스 - 회원가입 개발 (#7)
  src/main/java/com/example/miniprojectbe/controller/MemberController.java
  src/main/java/com/example/miniprojectbe/dto/MemberRequestDTO.java
  src/main/java/com/example/miniprojectbe/repository/MemberRepository.java
  src/main/java/com/example/miniprojectbe/service/Impl/MemberServiceImpl.java
  src/main/java/com/example/miniprojectbe/service/MemberService.java
Labels: For: API, Priority: High, Status: Completed, Type: Feature

#11 feat: 아이디 중복확인 기능구현
  src/main/java/com/example/miniprojectbe/controller/DuplicationController.java
  src/main/java/com/example/miniprojectbe/repository/UserRepository.java
  src/main/java/com/example/miniprojectbe/service/DuplicationService.java
  src/main/java/com/example/miniprojectbe/service/DuplicationServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#12 Feat: 회원 서비스 - 로그인 구현 (#5)
  build.gradle
  src/main/java/com/example/miniprojectbe/controller/DuplicationController.java
  src/main/java/com/example/miniprojectbe/controller/LogoutController.java
  src/main/java/com/example/miniprojectbe/controller/MemberController.java
  src/main/java/com/example/miniprojectbe/dto/MemberLoginDTO.java
  src/main/java/com/example/miniprojectbe/entity/Item.java
  src/main/java/com/example/miniprojectbe/jwt/JwtFilter.java
  src/main/java/com/example/miniprojectbe/jwt/JwtProperties.java
  src/main/java/com/example/miniprojectbe/jwt/JwtProvider.java
  src/main/java/com/example/miniprojectbe/repository/MemberRepository.java
  src/main/java/com/example/miniprojectbe/repository/UserRepository.java
  src/main/java/com/example/miniprojectbe/security/SecurityConfig.java
  src/main/java/com/example/miniprojectbe/service/DuplicationService.java
  src/main/java/com/example/miniprojectbe/service/DuplicationServiceImpl.java
  src/main/java/com/example/miniprojectbe/service/Impl/MemberServiceImpl.java
  src/main/java/com/example/miniprojectbe/service/LogoutService.java
  src/main/java/com/example/miniprojectbe/service/MemberService.java
  src/main/java/com/example/miniprojectbe/service/impl/MemberServiceImpl.java
  src/main/resources/application.properties
Labels: For: API, Priority: High, Status: In Progress, Type: Feature

#14 Feat: 회원 서비스 - 비밀번호 암호화 기능 추가 (#13)
  src/main/java/com/example/miniprojectbe/security/SecurityConfig.java
  src/main/java/com/example/miniprojectbe/service/impl/MemberServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#19 Feat: 회원 서비스 - 비밀번호 찾기 기능 구현 (#18)
  build.gradle
  src/main/java/com/example/miniprojectbe/controller/MemberController.java
  src/main/java/com/example/miniprojectbe/dto/MailDTO.java
  src/main/java/com/example/miniprojectbe/repository/MemberRepository.java
  src/main/java/com/example/miniprojectbe/security/SecurityConfig.java
  src/main/java/com/example/miniprojectbe/service/MemberService.java
  src/main/java/com/example/miniprojectbe/service/impl/CreateMailAndUpdatePwServiceImpl.java
  src/main/java/com/example/miniprojectbe/service/impl/MemberServiceImpl.java
  src/main/java/com/example/miniprojectbe/service/impl/SendMailServiceImpl.java
  src/main/resources/application.yml
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#20 Feature/#16 search2 카테고리별 조회 서비스 - 정기예금, 적금, 주택담보대출, 전세자금대출 조회 기능 개발
  src/main/java/com/example/miniprojectbe/controller/MemberController.java
  src/main/java/com/example/miniprojectbe/controller/SearchListController.java
  src/main/java/com/example/miniprojectbe/dto/DepositResponseDTO.java
  src/main/java/com/example/miniprojectbe/dto/LoanResponseDTO.java
  src/main/java/com/example/miniprojectbe/dto/SearchListRequestDTO.java
  src/main/java/com/example/miniprojectbe/entity/Deposit.java
  src/main/java/com/example/miniprojectbe/entity/Item.java
  src/main/java/com/example/miniprojectbe/entity/Loan.java
  src/main/java/com/example/miniprojectbe/repository/DepositRepository.java
  src/main/java/com/example/miniprojectbe/repository/LoanRepository.java
  src/main/java/com/example/miniprojectbe/security/SecurityConfig.java
  src/main/java/com/example/miniprojectbe/service/MemberService.java
  src/main/java/com/example/miniprojectbe/service/SearchListService.java
  src/main/java/com/example/miniprojectbe/service/impl/MemberServiceImpl.java
  src/main/java/com/example/miniprojectbe/service/impl/SearchListServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#22 Feat: 장바구니 서비스 - 장바구니 담기, 장바구니 조회 기능 개발 (#15)
  src/main/java/com/example/miniprojectbe/controller/BasketController.java
  src/main/java/com/example/miniprojectbe/dto/BasketId.java
  src/main/java/com/example/miniprojectbe/dto/BasketResponseDTO.java
  src/main/java/com/example/miniprojectbe/repository/BasketRepository.java
  src/main/java/com/example/miniprojectbe/repository/ItemRepository.java
  src/main/java/com/example/miniprojectbe/service/BasketService.java
  src/main/java/com/example/miniprojectbe/service/ItemService.java
  src/main/java/com/example/miniprojectbe/service/MemberService.java
  src/main/java/com/example/miniprojectbe/service/impl/BasketServiceImpl.java
  src/main/java/com/example/miniprojectbe/service/impl/ItemServiceImpl.java
  src/main/java/com/example/miniprojectbe/service/impl/MemberServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#25 Feature/#24 paging 서비스 - 카테고리별 조회시 10개씩 페이징(무한스크롤) 기능 개발
  src/main/java/com/example/miniprojectbe/controller/SearchListController.java
  src/main/java/com/example/miniprojectbe/repository/DepositRepository.java
  src/main/java/com/example/miniprojectbe/repository/LoanRepository.java
  src/main/java/com/example/miniprojectbe/service/SearchListService.java
  src/main/java/com/example/miniprojectbe/service/impl/SearchListServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#26 Feat: 회원 서비스 - 회원정보 수정/조회 개발 (#23)
  src/main/java/com/example/miniprojectbe/controller/MemberController.java
  src/main/java/com/example/miniprojectbe/dto/MemberInfoResponseDTO.java
  src/main/java/com/example/miniprojectbe/dto/MemberUpdateRequestDTO.java
  src/main/java/com/example/miniprojectbe/entity/Member.java
  src/main/java/com/example/miniprojectbe/jwt/JwtProvider.java
  src/main/java/com/example/miniprojectbe/repository/BlacklistRepository.java
  src/main/java/com/example/miniprojectbe/service/MemberService.java
  src/main/java/com/example/miniprojectbe/service/impl/BasketServiceImpl.java
  src/main/java/com/example/miniprojectbe/service/impl/MemberServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#31 Feat: 추천 서비스 - 회원 정보(은행, 상품종류)에 맞는 상품 추천 기능 구현 (#30)
  src/main/java/com/example/miniprojectbe/controller/RecommendController.java
  src/main/java/com/example/miniprojectbe/dto/MemberLoginDTO.java
  src/main/java/com/example/miniprojectbe/dto/RecommendDepositResponseDTO.java
  src/main/java/com/example/miniprojectbe/dto/RecommendLoanResponseDTO.java
  src/main/java/com/example/miniprojectbe/jwt/JwtFilter.java
  src/main/java/com/example/miniprojectbe/jwt/JwtProvider.java
  src/main/java/com/example/miniprojectbe/repository/DepositRepository.java
  src/main/java/com/example/miniprojectbe/repository/LoanRepository.java
  src/main/java/com/example/miniprojectbe/service/RecommendService.java
  src/main/java/com/example/miniprojectbe/service/impl/RecommendServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#33 Feat: 장바구니 서비스 - 장바구니 삭제(1개) | 비우기(전체 삭제) 기능 개발 (#27)
  src/main/java/com/example/miniprojectbe/controller/BasketController.java
  src/main/java/com/example/miniprojectbe/repository/BasketRepository.java
  src/main/java/com/example/miniprojectbe/service/BasketService.java
  src/main/java/com/example/miniprojectbe/service/impl/BasketServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#34 Refactor: 추천 서비스 로직 변경 및 엔티티 노출 수정
  src/main/java/com/example/miniprojectbe/controller/RecommendController.java
  src/main/java/com/example/miniprojectbe/dto/MemberLoginDTO.java
  src/main/java/com/example/miniprojectbe/jwt/JwtProvider.java
  src/main/java/com/example/miniprojectbe/service/ItemService.java
  src/main/java/com/example/miniprojectbe/service/MemberService.java
  src/main/java/com/example/miniprojectbe/service/impl/BasketServiceImpl.java
  src/main/java/com/example/miniprojectbe/service/impl/ItemServiceImpl.java
  src/main/java/com/example/miniprojectbe/service/impl/MemberServiceImpl.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Idea

#36 Feat: 추천 서비스 - 회원 맞춤 상품 추천 서비스 구현 (#35)
  src/main/java/com/example/miniprojectbe/controller/RecommendController.java
  src/main/java/com/example/miniprojectbe/dto/RecommendDepositResponseDTO.java
  src/main/java/com/example/miniprojectbe/dto/RecommendLoanResponseDTO.java
  src/main/java/com/example/miniprojectbe/repository/DepositRepository.java
  src/main/java/com/example/miniprojectbe/repository/LoanRepository.java
  src/main/java/com/example/miniprojectbe/service/RecommendService.java
  src/main/java/com/example/miniprojectbe/service/impl/RecommendServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#37 Feat: 장바구니 서비스 - 장바구니 추가 시 이미 장바구니에 존재하는 상품은 추가 안되게 하는 기능 개발 (#28)
  src/main/java/com/example/miniprojectbe/repository/BasketRepository.java
  src/main/java/com/example/miniprojectbe/service/impl/BasketServiceImpl.java
Labels: For: API, Priority: Low, Status: Completed, Type: Feature

#39 Feat: 상품 상세조회 서비스 - Deposit, Loan 구분해서 상세조회 기능 구현 #17
  src/main/java/com/example/miniprojectbe/controller/SelectDetailController.java
  src/main/java/com/example/miniprojectbe/dto/DepositDetailDTO.java
  src/main/java/com/example/miniprojectbe/dto/LoanDetailDTO.java
  src/main/java/com/example/miniprojectbe/repository/DepositRepository.java
  src/main/java/com/example/miniprojectbe/repository/LoanRepository.java
  src/main/java/com/example/miniprojectbe/security/SecurityConfig.java
  src/main/java/com/example/miniprojectbe/service/SelectDetailService.java
  src/main/java/com/example/miniprojectbe/service/impl/SelectDetailServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#40 Feature/#38 검색 서비스 페이징 처리로 변경, DTO에 itemId 속성 추가
  src/main/java/com/example/miniprojectbe/controller/ProductSearchController.java
  src/main/java/com/example/miniprojectbe/dto/DepositProductDTO.java
  src/main/java/com/example/miniprojectbe/dto/DepositResponseDTO.java
  src/main/java/com/example/miniprojectbe/dto/LoanProductDTO.java
  src/main/java/com/example/miniprojectbe/dto/LoanResponseDTO.java
  src/main/java/com/example/miniprojectbe/repository/DepositRepository.java
  src/main/java/com/example/miniprojectbe/repository/LoanRepository.java
  src/main/java/com/example/miniprojectbe/service/ProductSearchService.java
  src/main/java/com/example/miniprojectbe/service/impl/ProductSearchServiceImpl.java
Labels: For: API, Priority: Low, Status: Completed, Type: Feature

#41 Refactor: 장바구니 서비스 - 장바구니 조회 시 예적금/대출 따로 나눠서 보여줄 수 있게 분리 (api 분리) (#29)
  src/main/java/com/example/miniprojectbe/controller/BasketController.java
  src/main/java/com/example/miniprojectbe/repository/BasketRepository.java
  src/main/java/com/example/miniprojectbe/service/BasketService.java
  src/main/java/com/example/miniprojectbe/service/impl/BasketServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#43 Conf: CORS 관련 설정 추가 (#42)
  src/main/java/com/example/miniprojectbe/controller/BasketController.java
  src/main/java/com/example/miniprojectbe/controller/MemberController.java
  src/main/java/com/example/miniprojectbe/controller/ProductSearchController.java
  src/main/java/com/example/miniprojectbe/controller/RecommendController.java
  src/main/java/com/example/miniprojectbe/controller/SearchListController.java
  src/main/java/com/example/miniprojectbe/controller/SelectDetailController.java
  src/main/java/com/example/miniprojectbe/security/SecurityConfig.java
Labels: For: Backend, Priority: Critical, Status: Completed, Type: Feature

#45 Refactor: 로그인시 nullpointerException 해결, 장바구니 리스트 조회 코드 수정, PUBLIC_URLS 추가 (#44)
  src/main/java/com/example/miniprojectbe/dto/MemberLoginDTO.java
  src/main/java/com/example/miniprojectbe/jwt/JwtProvider.java
  src/main/java/com/example/miniprojectbe/repository/BasketRepository.java
  src/main/java/com/example/miniprojectbe/security/SecurityConfig.java
  src/main/java/com/example/miniprojectbe/service/impl/BasketServiceImpl.java
Labels: For: API, Priority: High, Status: Completed, Type : Bug

#48 Feature/#46 구매 서비스 - 구매(신청), 조회, 구매 취소 기능 개발
  src/main/java/com/example/miniprojectbe/controller/PurchaseController.java
  src/main/java/com/example/miniprojectbe/dto/PurchaseId.java
  src/main/java/com/example/miniprojectbe/dto/PurchaseResponseDTO.java
  src/main/java/com/example/miniprojectbe/entity/Purchase.java
  src/main/java/com/example/miniprojectbe/repository/PurchaseRepository.java
  src/main/java/com/example/miniprojectbe/service/PurchaseService.java
  src/main/java/com/example/miniprojectbe/service/impl/PurchaseServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#49 Conf: URL명 수정 및 https 설정 관련 gitignore 추가
  .gitignore
  src/main/java/com/example/miniprojectbe/controller/BasketController.java
  src/main/java/com/example/miniprojectbe/controller/MemberController.java
  src/main/java/com/example/miniprojectbe/controller/ProductSearchController.java
  src/main/java/com/example/miniprojectbe/controller/RecommendController.java
  src/main/java/com/example/miniprojectbe/controller/SearchListController.java
  src/main/java/com/example/miniprojectbe/controller/SelectDetailController.java
  src/main/resources/application.yml
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Maintenance

#52 Feat: 상품 신청 시 메일 전송 서비스 구현
  .github/workflows/main.yml
  .gitignore
  appspec.yml
  deploy.sh
  src/main/java/com/example/miniprojectbe/controller/MemberController.java
  src/main/java/com/example/miniprojectbe/controller/PurchaseController.java
  src/main/java/com/example/miniprojectbe/service/impl/CreateMailServiceImpl.java
  src/main/resources/keystore.p12
  src/test/java/com/example/miniprojectbe/MiniProjectBeApplicationTests.java
Labels: For: API, Priority: Low, Status: Completed, Type: Feature

#53 Feat: 상품 신청 시 메일 전송 서비스 구현
  src/main/java/com/example/miniprojectbe/controller/MemberController.java
  src/main/java/com/example/miniprojectbe/controller/PurchaseController.java
  src/main/java/com/example/miniprojectbe/service/impl/CreateMailServiceImpl.java
Labels: For: API, Priority: Low, Status: Completed, Type: Feature

#55 Refactor: 관심상품 삭제 기능 수정 (#54)
  src/main/java/com/example/miniprojectbe/controller/BasketController.java
  src/main/java/com/example/miniprojectbe/entity/Basket.java
  src/main/java/com/example/miniprojectbe/entity/BasketId.java
  src/main/java/com/example/miniprojectbe/entity/Purchase.java
  src/main/java/com/example/miniprojectbe/entity/PurchaseId.java
  src/main/java/com/example/miniprojectbe/repository/BasketRepository.java
  src/main/java/com/example/miniprojectbe/repository/PurchaseRepository.java
  src/main/java/com/example/miniprojectbe/service/BasketService.java
  src/main/java/com/example/miniprojectbe/service/impl/BasketServiceImpl.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Maintenance

#56 Refactor: 관심상품 삭제 기능 수정 (#54)
  .github/workflows/main.yml
  src/main/java/com/example/miniprojectbe/controller/BasketController.java
  src/main/java/com/example/miniprojectbe/entity/Basket.java
  src/main/java/com/example/miniprojectbe/entity/BasketId.java
  src/main/java/com/example/miniprojectbe/entity/Purchase.java
  src/main/java/com/example/miniprojectbe/entity/PurchaseId.java
  src/main/java/com/example/miniprojectbe/repository/BasketRepository.java
  src/main/java/com/example/miniprojectbe/repository/PurchaseRepository.java
  src/main/java/com/example/miniprojectbe/service/BasketService.java
  src/main/java/com/example/miniprojectbe/service/impl/BasketServiceImpl.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Maintenance

#58 Feat: 프론트 요청사항 추가 - 로그인시 이름 추가, 관심상품 유/무 확인, 신청한 상품 갯수 API #57
  src/main/java/com/example/miniprojectbe/controller/PurchaseController.java
  src/main/java/com/example/miniprojectbe/controller/SelectDetailController.java
  src/main/java/com/example/miniprojectbe/dto/DepositDetailDTO.java
  src/main/java/com/example/miniprojectbe/dto/LoanDetailDTO.java
  src/main/java/com/example/miniprojectbe/repository/PurchaseRepository.java
  src/main/java/com/example/miniprojectbe/service/PurchaseService.java
  src/main/java/com/example/miniprojectbe/service/SelectDetailService.java
  src/main/java/com/example/miniprojectbe/service/impl/MemberServiceImpl.java
  src/main/java/com/example/miniprojectbe/service/impl/PurchaseServiceImpl.java
  src/main/java/com/example/miniprojectbe/service/impl/SelectDetailServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#59 Feat: 프론트 요청사항 추가 - 로그인시 이름 추가, 관심상품 유/무 확인, 신청한 상품 갯수 API #57
  src/main/java/com/example/miniprojectbe/controller/PurchaseController.java
  src/main/java/com/example/miniprojectbe/controller/SelectDetailController.java
  src/main/java/com/example/miniprojectbe/dto/DepositDetailDTO.java
  src/main/java/com/example/miniprojectbe/dto/LoanDetailDTO.java
  src/main/java/com/example/miniprojectbe/repository/PurchaseRepository.java
  src/main/java/com/example/miniprojectbe/service/PurchaseService.java
  src/main/java/com/example/miniprojectbe/service/SelectDetailService.java
  src/main/java/com/example/miniprojectbe/service/impl/MemberServiceImpl.java
  src/main/java/com/example/miniprojectbe/service/impl/PurchaseServiceImpl.java
  src/main/java/com/example/miniprojectbe/service/impl/SelectDetailServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#62 Refactor: 헤더가 null로 들어올 경우 권한 부여되는 오류 수정, PUBLIC_URLS의 url명 수정 (#61)
  src/main/java/com/example/miniprojectbe/jwt/JwtFilter.java
  src/main/java/com/example/miniprojectbe/security/SecurityConfig.java
Labels: For: Backend, Priority: High, Status: Completed, Type: Maintenance

#63 Refactor: 헤더가 null로 들어올 경우 권한 부여되는 오류 수정, PUBLIC_URLS의 url명 수정 (#61)
  src/main/java/com/example/miniprojectbe/jwt/JwtFilter.java
  src/main/java/com/example/miniprojectbe/security/SecurityConfig.java
Labels: For: Backend, Priority: High, Status: Completed, Type: Maintenance

#64 Refactor: 신청취소 후 재신청 관련 로직 추가 및 신청완료된 건수만 카운트하도록 수정
  README.md
  src/main/java/com/example/miniprojectbe/entity/Purchase.java
  src/main/java/com/example/miniprojectbe/repository/PurchaseRepository.java
  src/main/java/com/example/miniprojectbe/service/impl/PurchaseServiceImpl.java
Labels: For: Backend, Priority: High, Status: Completed, Type : Bug

#66 Refactor: 신청취소 후 재신청 관련 로직 추가 및 신청완료된 건수만 카운트하도록 수정
  src/main/java/com/example/miniprojectbe/entity/Purchase.java
  src/main/java/com/example/miniprojectbe/repository/PurchaseRepository.java
  src/main/java/com/example/miniprojectbe/service/impl/PurchaseServiceImpl.java
Labels: For: Backend, Priority: High, Status: Completed, Type : Bug

#67 Refactor : 상품신청 목록 조회기능 수정 / 페이징 처리에서 전체 출력으로 변경
  src/main/java/com/example/miniprojectbe/controller/PurchaseController.java
  src/main/java/com/example/miniprojectbe/repository/PurchaseRepository.java
  src/main/java/com/example/miniprojectbe/service/PurchaseService.java
  src/main/java/com/example/miniprojectbe/service/impl/PurchaseServiceImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#68 Refactor : 상품신청 목록 조회기능 수정 / 페이징 처리에서 전체 출력으로 변경
  src/main/java/com/example/miniprojectbe/controller/PurchaseController.java
  src/main/java/com/example/miniprojectbe/repository/PurchaseRepository.java
  src/main/java/com/example/miniprojectbe/service/PurchaseService.java
  src/main/java/com/example/miniprojectbe/service/impl/PurchaseServiceImpl.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Feature

#70 Refactor: 상품 신청 취소 시 시간 업데이트 되도록 변경
  src/main/java/com/example/miniprojectbe/entity/Purchase.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#71 Refactor: 상품 신청 취소 시 시간 업데이트 되도록 변경
  src/main/java/com/example/miniprojectbe/entity/Purchase.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#72 Refactor: 정기예금/적금 맞춤추천 정렬 변경
  README.md
  src/main/java/com/example/miniprojectbe/repository/DepositRepository.java
  src/main/java/com/example/miniprojectbe/service/impl/RecommendServiceImpl.java
Labels: For: API, Priority: Low, Status: Completed, Type: Maintenance

#73 Refactor: 정기예금/적금 맞춤추천 정렬 변경
  src/main/java/com/example/miniprojectbe/repository/DepositRepository.java
  src/main/java/com/example/miniprojectbe/service/impl/RecommendServiceImpl.java
Labels: For: API, Priority: Low, Status: Completed, Type: Maintenance
